FROM python:3.12-slim

WORKDIR /app

# Instala ferramentas básicas
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    pandoc \
    && rm -rf /var/lib/apt/lists/*

COPY . /app

EXPOSE 8000

CMD ["python", "scripts/generators/python/serve_site.py", "-p", "8000"]
